stages:
  intent_00_download_phoneme_dictionary:
    cmd: >-
      python pipeline/download_phoneme_dictionary.py
      --output-dir data/phoneme_dictionary
    deps:
      - pipeline/download_phoneme_dictionary.py
    outs:
      - data/phoneme_dictionary/

  intent_01_generate_phrases:
    cmd: >-
      python pipeline/stages/intent_01_generate_phrases.py
      --input-phrases scripts/intent_prediction/01_input_phrases.csv
      --output-dir data/intent_01_generate_phrases
    deps:
      - pipeline/
      - scripts/intent_prediction/01_input_phrases.csv
    outs:
      - data/intent_01_generate_phrases/
    params:
      - pipeline.input_phrases_path
      - pipeline.variations_per_phrase
      - pipeline.subsample_rate
      - stages.generate_phrases.repeat_modifier_chance
      - stages.generate_phrases.pleasantry_chance
      - stages.generate_phrases.hesitation_chance
      - stages.generate_phrases.spelling_variant_chance
      - stages.generate_phrases.case_variant_chance

  intent_02_compute_vocab:
    cmd: >-
      python pipeline/stages/intent_02_compute_vocab.py
      --input-manifest-dir data/intent_01_generate_phrases
      --output-dir data/intent_02_compute_vocab
      --phoneme-dict data/phoneme_dictionary/cmudict-0.7b
    deps:
      - data/intent_01_generate_phrases/
      - data/phoneme_dictionary/cmudict-0.7b
      - pipeline/
    outs:
      - data/intent_02_compute_vocab/

  speech_01_generate_samples:
    cmd: >-
      python pipeline/stages/speech_01_generate_samples.py
      --input-manifest-dir data/intent_01_generate_phrases
      --output-dir data/speech_01_generate_samples
    deps:
      - data/intent_01_generate_phrases/
      - pipeline/
    outs:
      - data/speech_01_generate_samples/:
          persist: true
    params:
      - pipeline.subsample_rate
      - stages.generate_speech_samples.speech_rate_min
      - stages.generate_speech_samples.speech_rate_max
