pipeline:
  input_phrases_path: scripts/intent_prediction/01_input_phrases.csv
  variations_per_phrase: 20
  subsample_rate: 200

stages:
  generate_phrases:
    repeat_modifier_chance: 0.2
    pleasantry_chance: 0.3
    hesitation_chance: 0.3
    spelling_variant_chance: 0.1
    case_variant_chance: 0.2
  generate_speech_samples:
    speech_rate_min: -10
    speech_rate_max: 20
  add_delays:
    prefix_vary_probability: 0.333
    prefix_min_s: 0.1
    prefix_max_s: 0.5
    suffix_vary_probability: 0.333
    suffix_min_s: 0.1
    suffix_max_s: 0.5
