trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  applicationVersion: '1.0.0.$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Download NuGet packages
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build ($(buildConfiguration))
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Run unit tests ($(buildConfiguration))
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '**\AdaptiveRemote.csproj'
    msbuildArgs: '/t:Restore,Publish /p:PublishProfile=ClickOnceProfile /p:ApplicationVersion=$(applicationVersion) /p:PublishDir="$(Build.ArtifactStagingDirectory)\installer" /p:PublishReadyToRun=True'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\installer'
    ArtifactName: 'installer'
    publishLocation: 'Container'