<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AdaptiveRemote.EndtoEndTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="StreamJsonRpc" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdaptiveRemote.App\AdaptiveRemote.App.csproj" />
  </ItemGroup>

</Project>
