<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AdaptiveRemote.EndtoEndTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
    <PackageReference Include="StreamJsonRpc" Version="2.19.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdaptiveRemote.App\AdaptiveRemote.App.csproj" />
  </ItemGroup>

</Project>
