//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveRemote.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaptiveRemote.Logging.LoggingMessages", typeof(LoggingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in speech recognition loop: {0}.
        /// </summary>
        internal static string ConversationController_Error {
            get {
                return ResourceManager.GetString("ConversationController_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing speech recognition: {0}.
        /// </summary>
        internal static string ConversationController_ErrorDuringStartup {
            get {
                return ResourceManager.GetString("ConversationController_ErrorDuringStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed command &apos;{0}&apos;.
        /// </summary>
        internal static string ConversationController_Executed {
            get {
                return ResourceManager.GetString("ConversationController_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command &apos;{0}&apos;.
        /// </summary>
        internal static string ConversationController_Executing {
            get {
                return ResourceManager.GetString("ConversationController_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for attention.
        /// </summary>
        internal static string ConversationController_ListenForAttention {
            get {
                return ResourceManager.GetString("ConversationController_ListenForAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for commands.
        /// </summary>
        internal static string ConversationController_ListenForCommands {
            get {
                return ResourceManager.GetString("ConversationController_ListenForCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized &apos;{0}&apos; as &apos;{1}&apos;.
        /// </summary>
        internal static string ConversationController_Recognized {
            get {
                return ResourceManager.GetString("ConversationController_Recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting after {0} error(s).
        /// </summary>
        internal static string ConversationController_Retrying {
            get {
                return ResourceManager.GetString("ConversationController_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not restarting after {0} error(s).
        /// </summary>
        internal static string ConversationController_RetryLimitReached {
            get {
                return ResourceManager.GetString("ConversationController_RetryLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string ConversationController_Stopped {
            get {
                return ResourceManager.GetString("ConversationController_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string ConversationController_Stopping {
            get {
                return ResourceManager.GetString("ConversationController_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized an unknown command: {0}.
        /// </summary>
        internal static string ConversationController_UnknownCommand {
            get {
                return ResourceManager.GetString("ConversationController_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling RecognizeAsyncCancel
        ///{0}.
        /// </summary>
        internal static string ListeningController_RecognizeAsyncCancelError {
            get {
                return ResourceManager.GetString("ListeningController_RecognizeAsyncCancelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calling RecognizeAsync
        ///{0}.
        /// </summary>
        internal static string ListeningController_RecognizeAsyncError {
            get {
                return ResourceManager.GetString("ListeningController_RecognizeAsyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening={0} ({1} listen, {2} pause).
        /// </summary>
        internal static string ListeningController_State {
            get {
                return ResourceManager.GetString("ListeningController_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating listen state
        ///{0}.
        /// </summary>
        internal static string ListeningController_UpdateListenStateError {
            get {
                return ResourceManager.GetString("ListeningController_UpdateListenStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was cancelled..
        /// </summary>
        internal static string SpeechRecognition_CancelledListeningMethod {
            get {
                return ResourceManager.GetString("SpeechRecognition_CancelledListeningMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in {0}
        ///{1}.
        /// </summary>
        internal static string SpeechRecognition_ErrorInListeningMethod {
            get {
                return ResourceManager.GetString("SpeechRecognition_ErrorInListeningMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Enabled={1}.
        /// </summary>
        internal static string SpeechRecognition_GrammarEnabled {
            get {
                return ResourceManager.GetString("SpeechRecognition_GrammarEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load &apos;{0}&apos;
        ///{1}.
        /// </summary>
        internal static string SpeechRecognition_GrammarFailedToLoad {
            get {
                return ResourceManager.GetString("SpeechRecognition_GrammarFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unload &apos;{0}&apos;
        ///{1}.
        /// </summary>
        internal static string SpeechRecognition_GrammarFailedToUnload {
            get {
                return ResourceManager.GetString("SpeechRecognition_GrammarFailedToUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already in progress.
        /// </summary>
        internal static string SpeechRecognition_ListeningMethodAlreadyInProgress {
            get {
                return ResourceManager.GetString("SpeechRecognition_ListeningMethodAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition Error: {0}.
        /// </summary>
        internal static string SpeechRecognition_RecognitionError {
            get {
                return ResourceManager.GetString("SpeechRecognition_RecognitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioSignalProblemOccurred:{0} at {3} ({1}) with AudioLevel:{2}.
        /// </summary>
        internal static string SpeechRecognitionEngine_AudioSignalProblemOccurred {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_AudioSignalProblemOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioState:{0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_AudioStateChanged {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_AudioStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected: {0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_Detected {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothesized: {0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_Hypothesized {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_Hypothesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Grammar {1}\n   Cancelled:{2}\n   Error: {0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_LoadGrammarCompleted {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_LoadGrammarCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition rejected: {0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_RecognitionRejected {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_RecognitionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognize completed: InputStreamEnded:{0} Cancelled:{1} BabbleTimeout:{2} InitialSilenceTimeout:{4}
        ///   Result:{5}
        ///   Error{3}.
        /// </summary>
        internal static string SpeechRecognitionEngine_RecognizeCompleted {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_RecognizeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized {0}.
        /// </summary>
        internal static string SpeechRecognitionEngine_Recognized {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_Recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizer update reached at {0} ({1}).
        /// </summary>
        internal static string SpeechRecognitionEngine_UpdateReached {
            get {
                return ResourceManager.GetString("SpeechRecognitionEngine_UpdateReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot say &apos;{0}&apos;; another phrase is already in progress..
        /// </summary>
        internal static string SpeechSynthesis_AlreadySpeaking {
            get {
                return ResourceManager.GetString("SpeechSynthesis_AlreadySpeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled saying &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_CancelledSaying {
            get {
                return ResourceManager.GetString("SpeechSynthesis_CancelledSaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saying &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_Saying {
            get {
                return ResourceManager.GetString("SpeechSynthesis_Saying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected voice &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_SelectedVoice {
            get {
                return ResourceManager.GetString("SpeechSynthesis_SelectedVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice not found: &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_VoiceNotFound {
            get {
                return ResourceManager.GetString("SpeechSynthesis_VoiceNotFound", resourceCulture);
            }
        }
    }
}
