namespace AdaptiveRemote.Logging;

internal enum Message
{
    SpeechRecognitionEngine_Recognized = 101,
    SpeechRecognitionEngine_RecognitionRejected = 102,
    SpeechRecognitionEngine_Hypothesized = 103,
    SpeechRecognitionEngine_Detected = 104,
    SpeechRecognitionEngine_UpdateReached = 105,
    SpeechRecognitionEngine_RecognizeCompleted = 106,
    SpeechRecognitionEngine_LoadGrammarCompleted = 107,
    SpeechRecognitionEngine_AudioStateChanged = 108,
    SpeechRecognitionEngine_AudioSignalProblemOccurred = 109,
    ConversationController_ErrorDuringStartup = 201,
    ConversationController_Stopping = 202,
    ConversationController_Stopped = 203,
    ConversationController_Error = 204,
    ConversationController_RetryLimitReached = 205,
    ConversationController_Retrying = 206,
    ConversationController_Recognized = 207,
    ConversationController_UnknownCommand = 208,
    ConversationController_ListenForAttention = 209,
    ConversationController_Executing = 210,
    ConversationController_Executed = 211,
    ConversationController_ListenForCommands = 212,
    SpeechRecognition_RecognitionError = 302,
    SpeechRecognition_CancelledListeningMethod = 303,
    SpeechRecognition_ErrorInListeningMethod = 304,
    SpeechRecognition_GrammarEnabled = 305,
    SpeechRecognition_ListeningMethodAlreadyInProgress = 308,
    SpeechRecognition_GrammarFailedToLoad = 309,
    SpeechRecognition_GrammarFailedToUnload = 310,
    SpeechSynthesis_SelectedVoice = 401,
    SpeechSynthesis_VoiceNotFound = 402,
    SpeechSynthesis_Saying = 403,
    SpeechSynthesis_CancelledSaying = 404,
    SpeechSynthesis_AlreadySpeaking = 405,
    SpeechSynthesis_SetSpeakingRate = 406,
    ListeningController_State = 501,
    ListeningController_RecognizeAsyncError = 502,
    ListeningController_RecognizeAsyncCancelError = 503,
    ListeningController_UpdateListenStateError = 504,
}
