using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using AdaptiveRemote.Backend.ApiTests.Support;
using AdaptiveRemote.Contracts;
using FluentAssertions;
using Reqnroll;

namespace AdaptiveRemote.Backend.ApiTests.StepDefinitions;

[Binding]
public class RawLayoutSteps
{
    private readonly ServiceContext _context;
    private RawLayout? _createdLayout;

    public RawLayoutSteps(ServiceContext context)
    {
        _context = context;
    }

    [Given(@"RawLayoutService is running")]
    public async Task GivenRawLayoutServiceIsRunning()
    {
        await _context.Fixture.StartServiceAsync("AdaptiveRemote.Backend.RawLayoutService");
    }

    [Given(@"a raw layout exists with name ""(.*)""")]
    public async Task GivenARawLayoutExistsWithName(string layoutName)
    {
        // Create a test layout
        RawLayout testLayout = new(
            Id: Guid.Empty, // Will be generated by the service
            UserId: "test-user", // Will be overridden by the service with authenticated user
            Name: layoutName,
            Elements: new List<RawLayoutElementDto>
            {
                new RawCommandDefinitionDto(
                    Type: CommandType.TiVo,
                    Name: "TestCommand",
                    Label: "Test",
                    Glyph: null,
                    SpeakPhrase: "test command",
                    Reverse: null,
                    CssId: "test-cmd",
                    GridRow: 0,
                    GridColumn: 0
                )
            },
            Version: 1,
            CreatedAt: DateTimeOffset.UtcNow,
            UpdatedAt: DateTimeOffset.UtcNow,
            ValidationResult: null
        );

        StringContent content = new(
            JsonSerializer.Serialize(testLayout, LayoutContractsJsonContext.Default.RawLayout),
            Encoding.UTF8,
            "application/json");

        HttpResponseMessage response = await _context.Fixture.HttpClient.PostAsync("/layouts/raw", content);
        response.StatusCode.Should().Be(HttpStatusCode.Created);

        string responseBody = await response.Content.ReadAsStringAsync();
        _createdLayout = JsonSerializer.Deserialize<RawLayout>(responseBody, LayoutContractsJsonContext.Default.RawLayout);
        _createdLayout.Should().NotBeNull();
    }

    [When(@"a test client calls POST \/layouts\/raw with a valid RawLayout body")]
    public async Task WhenATestClientCallsPostWithValidRawLayout()
    {
        RawLayout testLayout = new(
            Id: Guid.Empty,
            UserId: "test-user",
            Name: "New Test Layout",
            Elements: new List<RawLayoutElementDto>
            {
                new RawCommandDefinitionDto(
                    Type: CommandType.TiVo,
                    Name: "Up",
                    Label: "Up",
                    Glyph: "↑",
                    SpeakPhrase: "up",
                    Reverse: "Down",
                    CssId: "up-btn",
                    GridRow: 0,
                    GridColumn: 1
                )
            },
            Version: 1,
            CreatedAt: DateTimeOffset.UtcNow,
            UpdatedAt: DateTimeOffset.UtcNow,
            ValidationResult: null
        );

        StringContent content = new(
            JsonSerializer.Serialize(testLayout, LayoutContractsJsonContext.Default.RawLayout),
            Encoding.UTF8,
            "application/json");

        _context.LastResponse = await _context.Fixture.HttpClient.PostAsync("/layouts/raw", content);
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls GET \/layouts\/raw\/\{id\} for the created layout")]
    public async Task WhenATestClientCallsGetForTheCreatedLayout()
    {
        _createdLayout.Should().NotBeNull();
        _context.LastResponse = await _context.Fixture.HttpClient.GetAsync($"/layouts/raw/{_createdLayout!.Id}");
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls PUT \/layouts\/raw\/\{id\} with updated name ""(.*)""")]
    public async Task WhenATestClientCallsPutWithUpdatedName(string newName)
    {
        _createdLayout.Should().NotBeNull();

        RawLayout updatedLayout = _createdLayout! with { Name = newName };

        StringContent content = new(
            JsonSerializer.Serialize(updatedLayout, LayoutContractsJsonContext.Default.RawLayout),
            Encoding.UTF8,
            "application/json");

        _context.LastResponse = await _context.Fixture.HttpClient.PutAsync($"/layouts/raw/{_createdLayout.Id}", content);
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls DELETE \/layouts\/raw\/\{id\} for the created layout")]
    public async Task WhenATestClientCallsDeleteForTheCreatedLayout()
    {
        _createdLayout.Should().NotBeNull();
        _context.LastResponse = await _context.Fixture.HttpClient.DeleteAsync($"/layouts/raw/{_createdLayout!.Id}");
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"an unauthenticated client calls GET \/layouts\/raw")]
    public async Task WhenAnUnauthenticatedClientCallsGet()
    {
        HttpClient anonymousClient = _context.Fixture.CreateAnonymousHttpClient();
        _context.LastResponse = await anonymousClient.GetAsync("/layouts/raw");
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls GET \/layouts\/raw\/\{id\} with a random GUID")]
    public async Task WhenATestClientCallsGetWithRandomGuid()
    {
        Guid randomId = Guid.NewGuid();
        _context.LastResponse = await _context.Fixture.HttpClient.GetAsync($"/layouts/raw/{randomId}");
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls PUT \/layouts\/raw\/\{id\} with a random GUID and name ""(.*)""")]
    public async Task WhenATestClientCallsPutWithRandomGuid(string name)
    {
        Guid randomId = Guid.NewGuid();
        RawLayout layout = new(
            Id: randomId,
            UserId: "test-user",
            Name: name,
            Elements: Array.Empty<RawLayoutElementDto>(),
            Version: 1,
            CreatedAt: DateTimeOffset.UtcNow,
            UpdatedAt: DateTimeOffset.UtcNow,
            ValidationResult: null
        );

        StringContent content = new(
            JsonSerializer.Serialize(layout, LayoutContractsJsonContext.Default.RawLayout),
            Encoding.UTF8,
            "application/json");

        _context.LastResponse = await _context.Fixture.HttpClient.PutAsync($"/layouts/raw/{randomId}", content);
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls DELETE \/layouts\/raw\/\{id\} with a random GUID")]
    public async Task WhenATestClientCallsDeleteWithRandomGuid()
    {
        Guid randomId = Guid.NewGuid();
        _context.LastResponse = await _context.Fixture.HttpClient.DeleteAsync($"/layouts/raw/{randomId}");
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls POST \/layouts\/raw with an invalid RawLayout body")]
    public async Task WhenATestClientCallsPostWithInvalidRawLayout()
    {
        // Send malformed JSON
        StringContent content = new(
            "{\"Name\": \"Test\", \"InvalidField\": true}",
            Encoding.UTF8,
            "application/json");

        _context.LastResponse = await _context.Fixture.HttpClient.PostAsync("/layouts/raw", content);
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [When(@"a test client calls POST \/layouts\/raw with a RawLayout missing required fields")]
    public async Task WhenATestClientCallsPostWithMissingFields()
    {
        // Send JSON with only partial fields (missing Elements, Version, etc.)
        StringContent content = new(
            "{\"Name\": \"Incomplete Layout\"}",
            Encoding.UTF8,
            "application/json");

        _context.LastResponse = await _context.Fixture.HttpClient.PostAsync("/layouts/raw", content);
        _context.LastResponseBody = await _context.LastResponse.Content.ReadAsStringAsync();
    }

    [Then(@"the body is an empty RawLayout array")]
    public void ThenTheBodyIsAnEmptyRawLayoutArray()
    {
        _context.LastResponseBody.Should().NotBeNullOrEmpty();

        IReadOnlyList<RawLayout>? layouts = JsonSerializer.Deserialize<IReadOnlyList<RawLayout>>(
            _context.LastResponseBody!,
            LayoutContractsJsonContext.Default.IReadOnlyListRawLayout);

        layouts.Should().NotBeNull();
        layouts.Should().BeEmpty();
    }

    [Then(@"the response is 201 Created")]
    public void ThenTheResponseIsCreated()
    {
        _context.LastResponse.Should().NotBeNull();
        _context.LastResponse!.StatusCode.Should().Be(HttpStatusCode.Created);
    }

    [Then(@"the response is 204 No Content")]
    public void ThenTheResponseIsNoContent()
    {
        _context.LastResponse.Should().NotBeNull();
        _context.LastResponse!.StatusCode.Should().Be(HttpStatusCode.NoContent);
    }

    [Then(@"the body contains the created RawLayout with a generated Id")]
    public void ThenTheBodyContainsTheCreatedRawLayout()
    {
        _context.LastResponseBody.Should().NotBeNullOrEmpty();

        RawLayout? layout = JsonSerializer.Deserialize<RawLayout>(
            _context.LastResponseBody!,
            LayoutContractsJsonContext.Default.RawLayout);

        layout.Should().NotBeNull();
        layout!.Id.Should().NotBeEmpty();
        layout.Name.Should().Be("New Test Layout");
        layout.Elements.Should().HaveCount(1);
        layout.Version.Should().Be(1);
    }

    [Then(@"the body deserializes to the created RawLayout")]
    public void ThenTheBodyDeserializesToTheCreatedRawLayout()
    {
        _context.LastResponseBody.Should().NotBeNullOrEmpty();

        RawLayout? layout = JsonSerializer.Deserialize<RawLayout>(
            _context.LastResponseBody!,
            LayoutContractsJsonContext.Default.RawLayout);

        layout.Should().NotBeNull();
        layout!.Id.Should().Be(_createdLayout!.Id);
        layout.Name.Should().Be(_createdLayout.Name);
    }

    [Then(@"the returned layout has name ""(.*)""")]
    public void ThenTheReturnedLayoutHasName(string expectedName)
    {
        _context.LastResponseBody.Should().NotBeNullOrEmpty();

        RawLayout? layout = JsonSerializer.Deserialize<RawLayout>(
            _context.LastResponseBody!,
            LayoutContractsJsonContext.Default.RawLayout);

        layout.Should().NotBeNull();
        layout!.Name.Should().Be(expectedName);
    }

    [Then(@"the layout version is incremented")]
    public void ThenTheLayoutVersionIsIncremented()
    {
        _context.LastResponseBody.Should().NotBeNullOrEmpty();

        RawLayout? layout = JsonSerializer.Deserialize<RawLayout>(
            _context.LastResponseBody!,
            LayoutContractsJsonContext.Default.RawLayout);

        layout.Should().NotBeNull();
        _createdLayout.Should().NotBeNull();
        layout!.Version.Should().Be(_createdLayout!.Version + 1);
    }

    [Then(@"getting the layout by ID returns 404 Not Found")]
    public async Task ThenGettingTheLayoutByIdReturnsNotFound()
    {
        _createdLayout.Should().NotBeNull();
        HttpResponseMessage response = await _context.Fixture.HttpClient.GetAsync($"/layouts/raw/{_createdLayout!.Id}");
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }
}
