<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdaptiveRemote.Console\AdaptiveRemote.Console.csproj" />
  </ItemGroup>

  <Import Project="..\AdaptiveRemote.EndToEndTests.Host.Wpf\Features\FeatureFiles.includeproj" />

</Project>
