//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveRemote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoggingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaptiveRemote.LoggingMessages", typeof(LoggingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in speech recognition loop: {0}.
        /// </summary>
        internal static string SpeechController_Error {
            get {
                return ResourceManager.GetString("SpeechController_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing speech recognition: {0}.
        /// </summary>
        internal static string SpeechController_ErrorDuringStartup {
            get {
                return ResourceManager.GetString("SpeechController_ErrorDuringStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed command &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechController_Executed {
            get {
                return ResourceManager.GetString("SpeechController_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechController_Executing {
            get {
                return ResourceManager.GetString("SpeechController_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for attention.
        /// </summary>
        internal static string SpeechController_ListenForAttention {
            get {
                return ResourceManager.GetString("SpeechController_ListenForAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening for commands.
        /// </summary>
        internal static string SpeechController_ListenForCommands {
            get {
                return ResourceManager.GetString("SpeechController_ListenForCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechController_Recognized {
            get {
                return ResourceManager.GetString("SpeechController_Recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting after {0} error(s).
        /// </summary>
        internal static string SpeechController_Retrying {
            get {
                return ResourceManager.GetString("SpeechController_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not restarting after {0} error(s).
        /// </summary>
        internal static string SpeechController_RetryLimitReached {
            get {
                return ResourceManager.GetString("SpeechController_RetryLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string SpeechController_Stopped {
            get {
                return ResourceManager.GetString("SpeechController_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string SpeechController_Stopping {
            get {
                return ResourceManager.GetString("SpeechController_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized an unknown command: {0}.
        /// </summary>
        internal static string SpeechController_UnknownCommand {
            get {
                return ResourceManager.GetString("SpeechController_UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saying &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_Saying {
            get {
                return ResourceManager.GetString("SpeechSynthesis_Saying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected voice &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_SelectedVoice {
            get {
                return ResourceManager.GetString("SpeechSynthesis_SelectedVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice not found: &apos;{0}&apos;.
        /// </summary>
        internal static string SpeechSynthesis_VoiceNotFound {
            get {
                return ResourceManager.GetString("SpeechSynthesis_VoiceNotFound", resourceCulture);
            }
        }
    }
}
