<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\AdaptiveRemote\wwwroot\**\*.html;..\AdaptiveRemote\wwwroot\**\*.css;">
      <Link>wwwroot\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdaptiveRemote\AdaptiveRemote.csproj" />
  </ItemGroup>

</Project>
